version: '3'
services:
  gpsUtil:
    image: gpsutil
    container_name: gpsutilappcontainer
    ports:
      - "8081:8081"

  rewardsCentral:
    image: rewardscentral
    container_name: rewardappcontainer
    ports:
      - "8082:8082"

  tripPricer:
    image: trippricer
    container_name: tripappcontainer
    ports:
      - "8083:8083"

  TourGuide:
    depends_on:
      - gpsutil
      - trippricer
      - rewardscentral
    image: tourguide
    container_name: tourguideappcontainer
    ports:
      - "8080:8080"
