version: '3'
services:
  gpsUtil:
    image: gpsutilapp
    container_name: gpsutilappcontainer
    ports:
      - "8081:8081"

  rewardsCentral:
    image: rewardscentralapp
    container_name: rewardappcontainer
    ports:
      - "8082:8082"

  tripPricer:
    image: trippricerapp
    container_name: tripappcontainer
    ports:
      - "8083:8083"

  TourGuide:
    depends_on:
      - gpsutilapp
      - trippricerapp
      - rewardscentralapp
    image: tourguideapp
    container_name: tourguideappcontainer
    ports:
      - "8080:8080"
